### ISSUE TITLE
node clustering feature has been dropped accidentally

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#102]
It seems as though node clustering has been removed as a feature in one of our recent PRs.  Whoops. 

We need to: 
1) Reenable it
2) write a unit test to check it moving forward. 

It was a minor feature, so not an urgent issue.  However, it should be PR'd back in before v0.3

**Comment by jayqi** [comment]
It looks like [this line](https://github.com/UptakeOpenSource/pkgnet/blob/master/R/AbstractGraphReporter.R#L404) expects `self$orphanNodes` in camel case, but the active binding `orphan_nodes` [here](https://github.com/UptakeOpenSource/pkgnet/blob/master/R/AbstractGraphReporter.R#L66) is in snake case. And thanks to R's $ NULL behavior, it goes through silently.

**Comment by jayqi** [comment]
@bburns632 -- I have been thinking: this orphan node clustering implementation is fairly janky, and from what I've seen, doesn't actually improve the layout of the graphs at all (it's all spaced as if the orphan nodes were still there).

I think a better solution would be to set a threshold at which to remove the orphan nodes from the plot entirely.

**Comment by bburns632** [comment]
@jayqi Having seen a number of large graphs with 10+ orphan nodes, I agree the current clustering solution does not improve the layout of the graph.  The graph is still sized with the original nodes included.  However, I don't think eliminating them entirely from the report graph fits withe the goal of giving a full picture of a package.  

Let's explore hybrid solutions, maybe where orphan nodes are displayed in a separate pane or bullet pointed outside the visualization.  

This should only be an issue with the function graph, not the dependency graph.

**Comment by jameslamb** [comment]
Agree with everything @bburns632 said. I think the biggest thing that annoys me about current orphan node handling is that we lay them all out horizontally, meaning that having a bunch of orphaned things leads to a tiny hard-to-read plot.

The function and dependency graphs are fundamentally different graphs...dependency graph is a tree while the function graph is just a directed graph with an arbitrary number of connected components.

I think that for orphan nodes, we should set a width in in `# nodes` and then stack on the right like this (assume node_width = 4):

1 orphan
```
                                   *
<rest_of_graph>
```

5 orphans
```
                                    *
                            * * * *
<rest_of_graph> 
```

23 orphan nodes

```
                             * * *
                            * * * *
                            * * * *
                            * * * *
                            * * * *
<rest_of_graph> 
```

^ nodes didn't line up perfectly, but you get the point

**Comment by jayqi** [comment]
I played around with some other igraph layouts. I think it doesn't make sense to use hierarchical layouts for `FunctionReporter` and if we use something different, then we don't necessary need to do anything special for the orphan nodes.

See for lubridate:

`layout_as_circle`
<img width="300" alt="layout_as_circle" src="https://user-images.githubusercontent.com/2721979/49297544-a8d01300-f480-11e8-8e5c-0d09b3edab83.png">

`layout_with_graphopt`
<img width="300" alt="layout_with_graphopt" src="https://user-images.githubusercontent.com/2721979/49297548-abcb0380-f480-11e8-9775-e5130db41b24.png">

`layout_with_dh`
<img width="300" alt="layout_with_dh" src="https://user-images.githubusercontent.com/2721979/49297550-ae2d5d80-f480-11e8-896c-c30c349d449a.png">
