### ISSUE TITLE
Proposal: Prevent set_package after a package has already been set

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#106]
Right now, we have a lot of calculated stuff cached in the Reporters, e.g., nodes, edges, metrics. If a user overwrites the package by calling `set_package` again, then it invalidates those cached objects and so we have functionality to [`reset_cache`](https://github.com/UptakeOpenSource/pkgnet/blob/master/R/AbstractPackageReporter.R#L84) and wipe them out.

This has a downside in that having to worry about cache resetting adds complexity. As an example, it has led to bug #70. 

I propose that instead, we prevent users from overwriting the package set for a Reporter (i.e., if `private$private_pkg_name` exists, throw a fatal error if they try to use `set_package`).

**Comment by jayqi** [comment]
@jameslamb @bburns632 especially would like your input here.

To briefly summarize some discussion I had with @jameslamb last night: he asked why not just put the package in the constructor. We didn't want to do that because we want to instantiate `DefaultReporters` without specifying a package. @ngparas suggested we consider a [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern)

**Comment by jayqi** [comment]
I think probably a simpler solution is to just make the package setting part of the the constructor.

We can easily define [`DefaultReporters`](https://github.com/UptakeOpenSource/pkgnet/blob/master/R/DefaultReporters.R#L5) like:
```
DefaultReporters <- function() {
    return(list(
          SummaryReporter
        , DependencyReporter
        , FunctionReporter
    ))
}
```

and then [this part of `.BuildPackageReporters`](https://github.com/UptakeOpenSource/pkgnet/blob/master/R/CreatePackageReport.R#L111-L117) we instead have
```
pkg_reporters <- sapply(
          X = pkg_reporters
          , FUN = function(reporter){
              reporter$new(pkg_name, pkg_path)
              return(reporter)
          }
      )
```

**Comment by bburns632** [comment]
@jayqi with the significant changes you made this past month or two, do you see this change as more, less, or equally valuable as when it was proposed?
