### ISSUE TITLE
Should have a unit test around explicitly setting report_path

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#118]
You can pass `report_path` to `CreatePakageReport()` to tell it exactly where to write the output HTML file. Right now, we do not test that `pkgnet` actually respects that.

We should add a test that tries several different report paths and confirms that `pkgnet` wrote the file there.

**Comment by bburns632** [comment]
This is a must for next release.  This has been a big issue for programatic users of `pkgnet` (i.e. automated runs with package releases, etc.)

**Comment by jameslamb** [comment]
I'm gonna take this one right now
