### ISSUE TITLE
import knitr?

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#119]
Right now, `R CMD CHECK` throws this NOTE:

```
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘knitr’
  All declared Imports should be used.
```

This is a weird situation we're in because we are using `knitr` heavily in our Rmd templates and those are key parts of the library, but from R CMD CHECK's perspective it thinks we aren't actually using it because no source code in `R/` calls `knitr`.

Given that CRAN just accepted our last release with this note, maybe we don't need to do anything with this? Alternatively, we could add an `#' @import knitr` (or, my preference, pick a random function to `importFrom` in) to hack it.

My gut says just leave it alone until CRAN actually complains.

@jayqi @bburns632 what do you think?

**Comment by jayqi** [comment]
I'm fine with leaving it alone, or alternatively throwing it here since this is where it gets used sorta. https://github.com/UptakeOpenSource/pkgnet/blob/master/R/CreatePackageReport.R#L77

**Comment by bburns632** [comment]
Throw an `importFrom` in at that location.  Sounds good to me.

**Comment by jameslamb** [comment]
ummmmmmmmmmmmm now this check isn't showing up any more? I ran `test.sh` on master and got 

```
* checking dependencies in R code ... OK
```

**Comment by jameslamb** [comment]
I am on R 3.4.3 on the laptop I'm checking this on. Guess I should have reported environment info the first time I did this.

Not closing the issue yet.

**Comment by jameslamb** [comment]
I just ran CHECK with and without `--as-cran` on R3.5.1 on Windows and didn't see this note. I also ran it on 3.5.0 on Mac laptop and didn't see the note.

I'm closing this issue.
