### ISSUE TITLE
Non-standard files/directories found at top level (R CMD CHECK bug)

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#124]
As of our last check run, a few small things need to be fixed to get the package fully back into CRAN compliance

```
* checking top-level files ... NOTE
Non-standard files/directories found at top level:
  'pkgnet_0.2.1.9000.tar.gz' 'test.sh' 'vignettes_source'
```

This can be fixed by adding the relevant files / directories to `.Rbuildignore`

**Comment by bburns632** [comment]
With the cran test compliance issue fixed, we can now revert back to a
vignettes folder, no need for source.
