### ISSUE TITLE
FunctionReporter tricked by list tags and nonstandard evaluation name collisions

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#126]
If a list item has the same name as a function and it gets used with the `$` syntax, then `FunctionReporter` reporter can be tricked into thinking that the function was invoked. 

To reproduce, make a package (e.g., with `package.skeleton()` or `pkgKitten::kiten()`) with the following functions:
```
func_A <- function() {
    return('hello')
}

func_B <- function() {
    foo <- list()
    foo$func_A <- 1
    return(foo)
}
```

Running `FunctionReporter` on this package will give:
```
> myreporter$nodes
     node
1: func_A
2: func_B
> myreporter$edges
   SOURCE TARGET
1: func_A func_B
```

This occurs with both the `mvbutils::foodweb` implementation in v0.2.1 on CRAN and with the new implementation on master. 

### Update:

Also happens with nonstandard evaluation, e.g., with data.table.

Examples:
```
func_D <- function() {
    foo <- data.table::data.table(x = 'trick')
    foo[, func_A := 'treat']
}

func_E <- function() {
    foo <- data.table::data.table(func_A = 'trick')
    foo[, func_A]
}
```

Edges:
```
> myreporter$edges
   SOURCE TARGET
1: func_A func_B
2: func_A func_D
3: func_A func_E
```

When you parse:
```
> .parse_function(trickypackage::func_D)
 [1] "{"          "<-"         "foo"        "::"        
 [5] "data.table" "data.table" "\"trick\""  "["         
 [9] "foo"        ""           ":="         "func_A"    
[13] "\"treat\"" 
> .parse_function(trickypackage::func_E)
 [1] "{"          "<-"         "foo"        "::"        
 [5] "data.table" "data.table" "\"trick\""  "["         
 [9] "foo"        ""           "func_A"    
```

**Comment by jayqi** [comment]
I think some of these, especially nonstandard evaluation pitfalls, are impossible to avoid. 

However, I propose the following to work around the list item issue:

For parsing code that looks like `foo$bar`, I propose we drop the `bar` and pretend it doesn't exist for purposes of matching function names, in case there is a function named `bar` in the package. (R6 methods being a special case, we would make a special exception for `self$` and `private$` when we support R6.)

The reasoning is as follows:

- Even if `foo$bar` actually referred to a function, the name `bar` is the name in the list and not the name of the real function.
- In cases where `foo` is actually a function and we have `foo()$bar`, we still want to break it up and catch that `foo()` is being called.

@bburns632 @jameslamb interested in hearing your thoughts.

**Comment by jameslamb** [comment]
@jayqi I actually think this whole thing might be impossible.

You say "we'd have to make a special exception for `self$` and `private$` with R6" but actually any R6 method method could be called with "whatever name you gave the instance", right?

```
random_thing <- SomeR6Generator$new()

func_1 <- function(x){
    result <- x$some_method()
    return(result + 5)
}

func_1(random_thing)
```

I feel like we might not be able to avoid this.

**Comment by jayqi** [comment]
Right, so I'm saying internal to a class definition, you'd know about internal references with `self$` and `private$`. With initialized objects, you really don't have a good way to figure out what class it is.
