### ISSUE TITLE
Bug: FunctionReporter edge direction reversed; add Unit Test for edge direction

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#127]
A recent PR #120  ~risked reversing~ reversed the edge direction by accident.  We should have a unit test on the `baseballstats` package to ensure this is not a risk with future PRs.

**Comment by jayqi** [comment]
Our convention for FunctionReporter edge direction is in the vignette: https://uptakeopensource.github.io/pkgnet/articles/pkgnet-intro.html

> Functions or Dependencies are represented as nodes, and their dependent relationships are represented as edges (a.k.a. arcs or arrows). The direction of the edge points towards the node that is dependent on the other node.
