### ISSUE TITLE
verify and remove input checks functions in `.UpdateNodes`

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#13]
Within `R/PackageFunctionReporter.R`, the function `.UpdateNodes` has a handful of input check functions.  Confirm that the new, object oriented structure makes these checks unnecessary and then remove them.

**Comment by bburns632** [comment]
Same with `.UpdateNetworkMeasures` and other .Update... functions in that script

**Comment by jameslamb** [comment]
red PRs are the best PRs

**Comment by jameslamb** [comment]
See #58 . `.UpdateNetworkMeasures` and other functions are not a thing any more. Can confirm that objects are taking care of input checking. Going to close this issue
