### ISSUE TITLE
Colorblind accessibility of colors

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#130]
We should use colorblind-accessible when possible.

For example, the test coverage color palette right now uses a `red`-`green` color scale.
https://github.com/UptakeOpenSource/pkgnet/blob/master/R/PackageFunctionReporter.R#L108

We could instead try to pick a colorblind safe color scheme from http://colorbrewer2.org

**Comment by jameslamb** [comment]
For anyone coming to this issue from Google, I want to also note that you can list out all the colorblind palettes in `RColorBrewer` as follows:

```
RColorBrewer::display.brewer.all(colorblindFriendly=TRUE)
```

**Comment by jameslamb** [comment]
hey we can close this now that #141 was closed!
