### ISSUE TITLE
Revisiting the directionality of edges (Nov 2018)

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#131]
Right now we have a convention:
```
    # Convention: If B depends on A, then B is the TARGET 
    # and A is the SOURCE so that it looks like A -> B
```

This was chosen as the convention by democratic polling among pkgnet authors back about a year ago or so. 

I would like to reopen the discussion for the reason that our current convention disagrees with UML which a lot of other applications out there follow. 

# Unified Modeling Language (UML)

[UML](https://en.wikipedia.org/wiki/Unified_Modeling_Language) is a widely used modeling framework for software engineering that is also an [ISO standard](https://www.iso.org/standard/32620.html). 

For [diagramming dependencies](https://en.wikipedia.org/wiki/Dependency_(UML)):
> In the UML, this is indicated by a dashed line pointing from the dependent (or client) to the independent (or supplier) element. The arrow representing a Dependency specifies the direction of a relationship, not the direction of a process.

For [class diagrams showing inheritance](https://www.ibm.com/developerworks/rational/library/content/RationalEdge/sep04/bell/index.html)
> To model inheritance on a class diagram, a solid line is drawn from the child class (the class inheriting the behavior) with a closed, unfilled arrowhead (or triangle) pointing to the super class.

**Comment by jayqi** [comment]
I googled "dependency graph visualization" and clicked on a bunch of stuff on the first page. Everything I looked at either had no directionality or had directionality consistent with UML: dependent -> independent.

- [Haskell Tool Stack](https://docs.haskellstack.org/en/stable/dependency_visualization/) ([2,911 stars](https://github.com/commercialhaskell/stack))
- [objc-dependency-visualizer](https://github.com/PaulTaykalo/objc-dependency-visualizer) (1,265 stars)
- [gpdepgraph](https://github.com/kisielk/godepgraph) (351 stars)
- [dependency-cruiser](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md) (217 stars)

**Comment by jameslamb** [comment]
I think @jayqi  makes a pretty convincing point that we should switch the order of inheritance.

If we decide to, I think we need to pull this into v0.3.0 milestone since I want to do some publicity around that release and it would suck to get people into using `pkgnet` and then release a big breaking change in a followup release.

**Comment by jayqi** [comment]
I think this also makes more sense if we consider the network measures we calculate.

For example, [PageRank](https://en.wikipedia.org/wiki/PageRank):
> PageRank works by counting the number and quality of links to a page to determine a rough estimate of how important the website is. The underlying assumption is that more important websites are likely to receive more links from other websites.

In the `Independent -> Dependent` convention, a function is considered high-score if it has a dependency on functions that depends on a lot of other functions? This measures some sort of complexity of a function and not its importance in graph. People usually don't use PageRank in this way. 

Whereas in the `Dependent -> Independent` convention, a function is considered high-score if it is depended on by functions that are depended on by a lot of other functions. This is more in-line with the normal interpretation of PageRank, which measures importance of a node.

**Comment by bburns632** [comment]
Ok @jayqi & @jameslamb. You make a convincing argument.  What I am hearing is that there is a UML convention and adhering to that convention will make it easier to integrate with other packages and for them to integrate with us.  The only potential counterpoint I can think of is edge aesthetics which is subjective and a minor point comparatively. 

Let's fit this in the next release, v0.3.0.

**Comment by jayqi** [comment]
It's funny Sphinx is the only one that does it the other way. There's an [two-year-old open issue](https://github.com/sphinx-doc/sphinx/issues/2969) about it where people say it's more common to see the UML convention.
