### ISSUE TITLE
README should have a GIF showing the main functionality

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#146]
Creating an issue to capture the work @mattdzugan already told us he's doing.

The README should have a GIF showing the main things you get with `CreatePackageReport()`.

1. READMEs with animation >>>> static READMEs
2. The GIF @batpigandme made for us on our first release DEFINITELY helped our Twitter reach (thanks again, Mara!) so I'd like to have this for the v0.3.0 release.

**Comment by jameslamb** [comment]
@bburns632 I'm adding this to v0.3.0 release, feel free to change if you disagree

**Comment by batpigandme** [comment]
I'm guessing that enough has changed since 0.1.0 that it's not that helpful, but just in case, here's the [file](https://www.dropbox.com/s/g5v7yp4y4u0rp9y/pkgnet_function_network.gif?dl=0) from 0.1.0 (twitter converts GIFs to MP4s behind the scenes, which is so annoying)

**Comment by jameslamb** [comment]
@batpigandme hey thank you! Yeah a TON is changing, we have lots of cool new stuff to share soon 😀
