### ISSUE TITLE
improve handling of pkgdown site

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#148]
See comment from #147 

>I think we should remove pkgdown completely from the master branch. Instead, we should host off the gh-pages branch which @bburns632 manually pushes to. That would keep master clean, avoid "updated the pkgdown site" commits on the project, and make it more palatable to do custom stuff like writing a script to build the pkgdown site (doing things like fixing links).

**Comment by jameslamb** [comment]
Closing this issue would include:

* removing all `pkgdown` details from the master branch (other then the pkgdown.yml config)
* documenting this process in CONTRIBUTING.md
* setting up a gh-pages branch with appropriate branch permissions
* rebuilding pkgdown siet and pushing it to that gh-pages branch

The first two things can be done by anyone, the other 2 have to be a @bburns632 thing

**Comment by jayqi** [comment]
@jameslamb FYI: you said offline that you couldn't find the `gh-pages` option and you thought it had been removed.

It seems like from the documentation that GitHub requires the branch to exist before it shows up in the dropdown. If we push a `gh-pages` branch, I think it should show up.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

**Comment by jayqi** [comment]
However, I still think that potentially we might _not_ want to do this because we maybe better maintain a practice of keeping pkgdown and CRAN in sync if we bundle doing them together.

**Comment by jameslamb** [comment]
Hey good find! I agree with you though, we should just stick with `master` but only do it at release time.

I added #149 to document some of the conclusions we've reached here and in person about what to do at release time.

**Comment by jameslamb** [comment]
I'm going to mark this one "won't do" and close it.
