### ISSUE TITLE
Include pkgnet's own package report as vignette and/or pkgdown article

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#159]
I think it would be cool to have a sample package report that people can look at without needing to download or install pkgnet. 

We'll need to figure out the mechanics of if we need it as an .Rmd or if we can get away with separately built html, and how different it might be from our existing package report. 

This could also be a chance to make a reusable function that other package authors could use to generate package-reports-as-vignettes to include as part of their own packages.

**Comment by bburns632** [comment]
Interesting.  What about building a `pkgnet` pkgnet report within [the readme_figures folder](https://github.com/UptakeOpenSource/pkgnet/tree/master/readme_figures) and referencing the absolute URL in the README and on an Examples page on with website (created via customization of the yml file)?  

Same trick as the gif.

**Comment by jayqi** [comment]
Two options for a vignette:

# (1) Include pkgnet report asis

Reference: https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf

Basically, the `R.rsp` vignette rendering engine lets you put whatever static file in the `vignettes` directory alongside an `asis` metadata file, and it will simply copy it over when building vignettes. 

PROS:

- Use pkgnet reports as is, with pretty formatting and tabs

CONS:

- Requires an additional suggests dependency to work (R.rsp). Potentially annoying if we want to make it easy for someone else to add to their package. 
- Requires adding it as a vignette engine to DESCRIPTION (R.rsp). Potentially annoying if we want to make it easy for someone else to add to their package. 
- Doesn't work with pkgdown, which **only** supports knitr [open issue](https://github.com/r-lib/pkgdown/issues/781)

# (2) Make an html-vignette version

We can make another version of `package-report.rmd` except we move all the machinery of `CreatePackageReport` inside the rmd file rather than passing stuff in as parameters. 

PROS:

- Works with pkgdown

CONS:

- Some duplicated code in maintaining two rmd files.
- Will need to code-gen an actual rmd file from a template if we want a function to make it easy for people to add to their own package. 
- Not the standard formatting for pkgnet report. Won't be able to use tabs.

**Comment by jayqi** [comment]
This was resolved in two ways:

- #200 added `CreatePackageVignette`, and the resulting vignette was also added for pkgnet (See vignette [here](https://github.com/UptakeOpenSource/pkgnet/pull/200/files?file-filters%5B%5D=.Rd#diff-07d4b8bdcc97088baeb70b35043e93fc))
- #202 and #206 added the [pkgnet Gallery](https://uptakeopensource.github.io/pkgnet-gallery/docs/articles/pkgnet-gallery.html), where you can see pkgnet's report
