### ISSUE TITLE
Network Statistics are off

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#165]
Our network statistics are **WAY** off somehow.  Consider this example:

`pkgnet::CreatePackageReport("lubridate")`

# Package Dependencies
Looks at `stats` package.  It clearly has an inDegree of 1 and outDegree of 3.  However, in the table, the values are 3 and 0 respectively. 

![image](https://user-images.githubusercontent.com/24531403/51572060-d5455180-1e69-11e9-98b3-61e744eade1b.png)

# Functional Dependencies
`divide_duration_by_difftime` is listed as one of the largest inSubgraphs at 81.  However, **it has no edges**.  In the repo, it is mentioned just twice: the function dependency 

![image](https://user-images.githubusercontent.com/24531403/51571835-f194be80-1e68-11e9-9840-7dc51f43c538.png)

![image](https://user-images.githubusercontent.com/24531403/51571907-36205a00-1e69-11e9-9591-4be3d92fb165.png)

![image](https://user-images.githubusercontent.com/24531403/51572001-9b744b00-1e69-11e9-9b4b-802bdafb53cc.png)

This is a bug.

**Comment by jayqi** [comment]
I bet the cause is something like when you're calculating it and then assigning the columns to the data.table, it's in a different order, or maybe something like igraph dropping NAs and then it's tiling the shorter vector.

**Comment by bburns632** [comment]
@jayqi I'm pretty sure it's that.  Merges of out of order vectors.  Working on it now.
