### ISSUE TITLE
Package Report

### ISSUE THREAD

**Issue by patrick-boueri** [UptakeOpenSource/pkgnet#17]
I think the original intent of each PackageReporter was that it was able to knit a child markdown page, and give a high level summary stats, that could then be bundled into a single report for your package. Each page would have some intro about it, and a rank ordered list of "what do i do next if i want to fix this", as well as maybe some cool plots. I think this ordering should be pluggable but we can have sensible defaults.

For our current reporters this is what i envision:
- "Dependencies" has a rank ordered list of packages you inherit for limited functionality based on the number of dependencies they introduce and how often they are used within a package (relies on namespacing, also another good candidate for a reporter. Which functions are ambiguous)
- "Functions" has a centrality measure and ideally a testcoverage score, the product of which (with some edge conditioning) allows for you to know which test to write next.

Is this inline with everyone's thinking?

**Comment by jameslamb** [comment]
I love this idea, yeah. Instead of just plotting to the default graphics device (which we do right now), I think the "each reporter returns a child markdown" idea is super cool and would be valuable. 

I really really like the idea of also having some intro text for each reporter and some recommended steps to take. That's so powerful

**Comment by bburns632** [comment]
The plan for the dependencies sounds excellent.  What about a list of top 5 functions in the package that use said dependency.  That would help address how to remove that package. 

For functions, in addition to centrality and test coverage, total number of dependencies, and cyclomatic complexity comes to mind.  

I think centrality and total number of dependencies should align, but whichever comes across to the user more clearly as "hey-this-is-an-important-function" I'm cool with. 

Cyclomatic complexity helps highlight functions that should be rewritten or possibly refactored into smaller functions.  Test coverage would not address this.

**Comment by patrick-boueri** [comment]
Great! I'll make this my next PR. Also i dunno how to assign labels otherwise i would've. Is that a thing only OSS gurus can do?

**Comment by jameslamb** [comment]
I'm 99% sure anyone can do it, but not 100% sure. I'll go try messing with one on Frasco's `Metrics` package (where I know I'm not an admin) and report back

**Comment by jameslamb** [comment]
jk he didn't have any. I tried on `networkx` and can confirm that I couldn't change the labels on any of them.

We sent you an invite to be a contributor on this repo when we first started, which should give you the write to change them. But it says you haven't accepted. Need me to re-send it?

**Comment by jameslamb** [comment]
This one can safely be closed. Thanks to @patrick-boueri and @torpeterson for setting up the initial skeleton and making it easy to plug stuff in
