### ISSUE TITLE
Create a Gallery of pkgnet Reports

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#184]
As part of our website, let's include a gallery section which showcases a number of `pkgnet` reports, including `pkgnet` itself as described in #159.  

Possibly, we could host the reports (or vignettes) in a separate github repository and link to them within a section created via `pkgdown`.  For extra pizzazz, we could use webshot to capture an image of the network in each report and include it in the website.

**Comment by bburns632** [comment]
As an option, we could follow [ggplot2's gallery](https://github.com/ggplot2-exts/gallery) format.  However, seems like a lot of overhead.

**Comment by bburns632** [comment]
[rgallery](https://github.com/dgrtwo/rgallery) looks pretty sweet.  Exploring this.

**Comment by bburns632** [comment]
https://github.com/d3/d3/wiki/Gallery is also slick

**Comment by bburns632** [comment]
OK. I proved the concept of a table from raw HTML within a Gallery tab on the website using the [D3 wiki gallery](https://github.com/d3/d3/wiki/Gallery) code. 

The key was `<!--html_preserve--><!--\html_preserve-->` I found from https://github.com/rstudio/rmarkdown/issues/326.

I will make a PR with a four package gallery to get things started.

**Comment by jameslamb** [comment]
Can this be closed? Now that [the site is looking so good](https://uptakeopensource.github.io/pkgnet/index.html)
