### ISSUE TITLE
Reinstate tests

### ISSUE THREAD

**Issue by patrick-boueri** [UptakeOpenSource/pkgnet#19]
After i commented them all out 😬

**Comment by jameslamb** [comment]
tough but fair

**Comment by patrick-boueri** [comment]
Will slowly do this as we add in functionality

**Comment by jameslamb** [comment]
yeah for sure, we'll have to go one thing at a time with this

**Comment by jameslamb** [comment]
@bburns632 @patrick-boueri I'm gonna pick up this issue. Think trying to test everything will expose some more issues we haven't thought about yet.

We gotta be close!

**Comment by jameslamb** [comment]
We have 78% test coverage now. That's not perfect and our tests aren't exhaustive, but certainly enough to drop this issue
