### ISSUE TITLE
Exporting of Abstract Classes

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#190]
Currently, `AbstractGraphReporter` and `AbstractPackageReporter` are exported and available to users.

**Why we would want to export:**  we expect users to extend them and define their own custom reporters

**Why we would *not* want to export:** they don't work as-is and create unneeded public interfaces for pkgnet 

I don't expect users to create custom reporters, so my vote is to stop exporting them. 

@jameslamb @bburns632

**Comment by jameslamb** [comment]
I agree, let's bring them back inside

**Comment by bburns632** [comment]
Agree.  Also, by keeping them internal, maybe that will encourage
contributions?...
