### ISSUE TITLE
Write roxygen article for package

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#193]
We don't currently have a package-level roxygen documentation article. 

~Conventionally, the way this would be done is by documenting a NULL object in `pkgnet.R` with the name `pkgnet` and setting `@docType package`.~ Then users would be able to land there with `?pkgnet`. 

**UPDATE:** It looks like the standard way to do this nowadays is to document a string object with the value `"_PACKAGE"`. This is a special keyword for roxygen2 to know you're making a package documentation article, to create the right names, and to fill in some of the details (e.g., list of authors).

So the two things of note to do are:
- Document a string `"_PACKAGE"`
- Use `@keywords internal` so that you don't have a `pkgnet` and `pkgnet-package` article show up in the index, but they are still accessible if you `?pkgnet` or `?pkgnet-package`.

References: 
- ~[Hadley's *R packages* book](http://r-pkgs.had.co.nz/man.html#man-packages)~
- [dplyr's package documentation](https://github.com/tidyverse/dplyr/blob/master/R/dplyr.r)

**Comment by jameslamb** [comment]
oh wow good call. So this is how to write the thing that comes up when you do like `?ggplot2-package`?

I like this
