### ISSUE TITLE
The R CMD check unit test is irrelevant now

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#20]
We can remove this test since this is what Travis CI will do anyway:

https://github.com/UptakeOpenSource/pkgnet/blob/master/tests/testthat/test-repo_characteristics.R#L13

**Comment by jayqi** [comment]
I think this one is redundant with #19 since it's commented out right now anyways.

**Comment by jameslamb** [comment]
it's not. This one says "drop all that commented code"
