### ISSUE TITLE
Discussion: v0.5.0 Goal and Scope

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#208]
This is an open discussion to discuss the goal and scope of a future v0.5.0 release.  Feel free to use the feature ideas captured in the [issues page](https://github.com/UptakeOpenSource/pkgnet/issues) for inspiration and/or propose something completely new.  

The outcome of this conversation will heavily influence the goal of the [v0.5.0 milestone](https://github.com/UptakeOpenSource/pkgnet/issues).

**Comment by wdearden** [comment]
One cool feature would be if `pkgnet-gallery` watched CRAN and hosted `pkgnet` reports for every package like CRANberries does with DESCRIPTION files (http://dirk.eddelbuettel.com/cranberries/).

**Comment by jameslamb** [comment]
Looking at all those open issues, I think the target of v0.5.0 should be something like "extensibility". As we add those other features, let's consider whether we should re-do any of our abstractions and whether we should formally document how to write a `pkgnet` "plug-in" to integrate your own types of metrics.

**Comment by shivamx96** [comment]
The idea from @jameslamb appears to be quite useful.

**Comment by bburns632** [comment]
The goal for [v0.5.0](https://github.com/UptakeOpenSource/pkgnet/milestone/3) is now updated.
