### ISSUE TITLE
Error message for not-installed package isn't clear

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#210]
Currently if you don't have the package installed that you're trying to run pkgnet on, the error messages look something like:
```
INFO [2019-03-28 19:02:47] Checking installed packages...
FATAL [2019-03-28 19:02:47] pkgnet could not find a package called 'data.table'.
```
We should have the FATAL error message give the instruction that the user should install the package first.

**Comment by shivamx96** [comment]
Hey.
I'd like to work on this one. Can you help me with how to proceed?

**Comment by jayqi** [comment]
Hi @shivamx96, thank you! The functionality in pkgnet reporters for loading a package for analysis is defined in `AbstractPackageReporter`, which is the base class that all other reporters are built on top of. You should be able to find it in this file: https://github.com/UptakeOpenSource/pkgnet/blob/master/R/AbstractPackageReporter.R

Please let me know if you need any additional help after taking a look at that.

**Comment by shivamx96** [comment]
Should we just show the command to install the required package or also give the option to install it here itself?

**Comment by jayqi** [comment]
I think we can just say something like: "pkgnet could not find a package called <pkgname>. pkgnet only works with installed packages--please install it first." There isn't just one command to install, depending on whether a user needs to install it from CRAN, install it from local source, or install it from GitHub.

**Comment by shivamx96** [comment]
Hi @jayqi, I've done the changes on my fork in a branch named **fixing-error-for-not-installed-packages**. Please have a look and tell any other changes to be done or I shall submit PR.

**Comment by jayqi** [comment]
Hi @shivamx96, that's great! Take a quick look at our [CONTRIBUTING.md](https://github.com/UptakeOpenSource/pkgnet/blob/master/CONTRIBUTING.md#prs) if you haven't already, and go ahead and open a PR. It'll be easier for myself and the other maintainers to review your changes in an open PR than on your fork's branch.

**Comment by shivamx96** [comment]
No changes in unit tests are needed, I suppose?

**Comment by jameslamb** [comment]
@shivamx96 probably not for this one! Don't worry too much about making your code "perfect" before submitting a pull request, we'll ask for any additional changes there if they are needed.
