### ISSUE TITLE
Discussion: Remove pkgnet vignette example

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#213]
@jayqi , now that I've rendered the v0.4.0 draft website, I think we should reconsider posting `pkgnet-report.Rmd` to the articles page for a few reasons: 

1. I don't think it's clear that this is example output from `CreatePackageVignette()`. 
2. I'm not sure example report of any type is necessary on this articles page now that the gallery is up and running. 
3. The title is confusing as created, `pkgnet Package Report, by pkgnet`.  

Would you be open to submitting this as a gallery entry instead? We could retitle the two entries: `pkgnet (standard format)` and `pkgnet (vignette format)` or something similar.

**Comment by jayqi** [comment]
Yeah, I'm okay with that.

It also sounds like perhaps we should add some language to the vignette that it's generated by `CreatePackageVignette()`

**Comment by bburns632** [comment]
Thanks for the flexibility @jayqi.  Perhaps an html banner, custom coded for the gallery example, describing the situation would be beneficial.
