### ISSUE TITLE
Remove reliance on mvbutils

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#22]
`mvbutils::foodweb` is a key function used by the current version of `pkgnet`. That makes me nervous...`mvbutils` most recent release was in 2015, it has [no tests AFAICT](), and there is not clear package philosophy. Most of what's in that package is irrelevant to `pkgnet` and (in the spirit of what we're doing here) carrying it around as a shadow dependency seems like a risk we shouldn't tolerate.

Here's the core code for `foodweb`: https://github.com/markbravington/mvbutils/blob/97c07457e3af05c52ebc5dd241e7b048190dc7df/R/mvbutils.R#L3895

And where we use it: https://github.com/UptakeOpenSource/pkgnet/blob/8d7781dd3774b4abad4abccb11f2cd59a38e93d0/R/PackageFunctionReporter.R#L83

I propose that we contact the package maintainer for `mvbutils` and talk about the possibility of ripping `foodweb` out of his package, putting it into ours as a non-exported function, changing it to match our style and other standards, and adding him as an author on `pkgnet`. Thoughts?

**Comment by bburns632** [comment]
Yes, we'd be real hypocrites to create a R library the analysis of R libraries and leave this risky dependency in our package.  

I think they were lost in the migration to public giuthub, but there were shoutouts to `foodweb` authors for this function.  I'm fine with the above plan.

**Comment by jameslamb** [comment]
I made really good progress on this one today, needs a bit more work before it's at a state where the PR would be understandable.

Once I get it working, we' can consider whether what I have is truly a rip-out of `foodweb` (in which case we should contact the original author) or something new enough to not worry about it. Basically I'm trying to figure out how he answers the question "function A calls function B".
