### ISSUE TITLE
Group orphan nodes together above a threshold value

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#28]
Create a private variable `orphanNodeClusteringThreshold` and leverage `visNetwork::visClusteringByConnection` (or similar visNetwork function) to group orphan nodes together as one cluster node when there are more orphan nodes than the parameter, `orphanNodeClusteringThreshold`. 

Reason being that the graphs get super busy when there are a lot of orphan nodes.  See `lubridate`'s graph as an example.

**Comment by jayqi** [comment]
I think this is going to touch a lot of the same code as #26 so maybe wait until that PR is merged.

**Comment by jayqi** [comment]
I don't think `visNetwork::visClusteringByConnection` or any of the other `visClustering_` functions are the way to implement this. These functions are all intended for clustering connected nodes together. You can look at this vis.js example to see what the different functions do: http://visjs.org/examples/network/other/clustering.html

**Comment by jayqi** [comment]
Alright, I found a hack. If you assign each orphan node to the same `group` then you can cluster that group together. Example:

```
set.seed(124)
nodes <- data.frame(id = 1:10
                    , color = c(rep("blue", 6), rep("red", 3), rep("green", 1))
                    , group = c(rep(NA_character_,6), "orphan", rep(NA_character_, 2), "orphan")
                    )
edges <- data.frame(from = round(runif(6)*10), to = round(runif(6)*10))

visNetwork(nodes, edges) %>%
    visClusteringByGroup(groups = c("orphan"))
```

**Comment by jayqi** [comment]
@bburns632 I have changes that are mostly done that implements this. The problem I'm running into now is that `visNetwork::visHierarchicalLayout` and `visNetwork::visClusteringByGroup` don't seem to be compatible. When I have the hierarchical layout, then clustering just gets ignored.

**Comment by jayqi** [comment]
So there's good news and bad news.

The good news is that I got the clustering the work.

The bad news is that the clustering doesn't work well if you're using igraph to set layouts. Essentially we're pre-calculating display x-y coordinates using the full network. I guess maybe we can do something hacky when we calculate the coordinates to pretend they are all one node. 

![screen shot 2018-01-24 at 9 49 46 pm](https://user-images.githubusercontent.com/2721979/35369994-b03b1f00-0150-11e8-8802-b793d1c6ab8b.png)
