### ISSUE TITLE
Get pkgnet into CRAN compliance

### ISSUE THREAD

**Issue by patrick-boueri** [UptakeOpenSource/pkgnet#30]
Basically work through all the errors in the below command to get ready for cran release

R CMD CHECK --as-cran .

**Comment by jameslamb** [comment]
to start, someone could close #20

**Comment by jameslamb** [comment]
just checking in to say that at this moment, we are fully CRAN-compliant. Not closing the issue though...will close it after the first accepted push to CRAN

**Comment by jameslamb** [comment]
@bburns632 I ran this on the current master branch tonight. I think we are good to go!

There was one NOTE, but it was the standard license one that they will probably let us ignore.

```
R CMD BUILD pkgnet
R CMD CHECK pkgnet_0.1.0.tar.gz --as-cran
```
