### ISSUE TITLE
output nodes and edges of package dependency and function network

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#34]
Create a function to output the nodes & edge list to csv.  This will allow easier integration with other packages.

**Comment by jameslamb** [comment]
@bburns632 I am going to remove the `post-release` tag from this and other issues now that our first release is up on CRAN

**Comment by jayqi** [comment]
@bburns632 do you still think this is necessary now that you can get the `nodes` and `edges` data.tables via active bindings? Someone can easily just pop those into their csv writer of choice.

**Comment by bburns632** [comment]
@jayqi I no longer think it is necessary to provide csv creation functionality.  I think we may want to consider our deliverables for `pkgnet` as: 

1. the rendered and displayed HTML report
2. the saved HTML report (if requested) 
3. the returned R object

@jameslamb thoughts?

**Comment by jayqi** [comment]
Closing this issue as one can get the nodes and edges data.tables via active bindings and then easily just pop those into their csv writer of choice. Adding a csv writer feels unnecessary.

@jameslamb if you disagree feel free to reopen.
