### ISSUE TITLE
allow import of nodes&edges from csv

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#35]
In the spirit of integration with other packages, allow a network to be given to `pkgnet` in the form of a csv of nodes and a csv of edges.

**Comment by jayqi** [comment]
Per discussion in #37, this feature would add a lot of complexity but does not align well with the core purpose of pkgnet. pkgnet's value is primarily to extract the network in the first place.

**Comment by jameslamb** [comment]
I agree with @jayqi . Thanks for adding the label
