### ISSUE TITLE
allow import of igraph object

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#37]
In the spirit of integration with other packages, allow a network to be given to `pkgnet` in the form of an `igraph` object.  

[igraph](http://igraph.org/redirect.html) is a popular network analysis tool & format written in R, python, and c++.

**Comment by bburns632** [comment]
Similar to #34, now that pkgnet has matured, do we want this as a feature?

If this is an R package for analyzing other R packages ..., why import analysis from other packages? The graphs we create are all visualized with vizNetwork, so why go through pkgnet if you have already created the graph?

**Comment by jayqi** [comment]
Yeah, I don't see a lot of benefit to being able to let users provide an arbitrary igraph object. Most of the meat of what pkgnet is doing is that we have all this logic for extracting different types of networks related to packages.
