### ISSUE TITLE
appveyor testing is not set up

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#38]
Looking for someone to figure out how to configure appveyor testing for this repo. I've added the project to the `UptakeOpenSource` account with appveyor, just need someone to figure out how to create the `.appveyor.yml` that will run our tests

**Comment by jameslamb** [comment]
@bburns632 I agree with not attaching this to any milestone, but I do think we need to do it soon. Otherwise we're gonna get surprised by windows stuff at release time

**Comment by jameslamb** [comment]
I think this is lower-priority (maybe) with Travis adding preliminary support for windows: https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by bburns632** [comment]
This needs some configuring to Script mode.  #150 passes CRAN tests for windows but fails in AppVeyor with: 

```Build started
git clone -q https://github.com/UptakeOpenSource/pkgnet.git C:\projects\pkgnet
git fetch -q origin +refs/pull/150/merge:
git checkout -qf FETCH_HEAD
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.```
```
https://ci.appveyor.com/project/jameslamb/pkgnet/builds/21349478

**Comment by bburns632** [comment]
Escalated to bug now that it occurs with each PR tested.

**Comment by jameslamb** [comment]
@bburns632 yep sorry, I"m the worst. This is because I turned on appveyor for this repo but never configured it. The console makes it easy to confuse the `UptakeOpenSource` repo and your own fork (I was trying to turn it on for my own fork).

I just disabled it for now, so you shouldn't see it anymore.

**Comment by BruceZhaoR** [comment]
@jameslamb Need help on this?

**Comment by jameslamb** [comment]
@BruceZhaoR yeah we'd love if you pick it up!

Be warned...our setup is kind of wild. Because we are a package that does stuff to packages, we set up multiple fake packages as test data (https://github.com/UptakeOpenSource/pkgnet/tree/master/inst) and to get around CRAN's restrictions on what you can do we do some crazy stuff to install them.

I recommend you:

1. Start by trying normal appveyor setup (ignore my comments from earlier on here about Windows-on-Travis, it's not there for R yet)
2. We'll help diagnose issues related to our weird testing setup as you work through it.

I'll assign this issue to you and turn this project back on in the appveyor console.

Thanks!!!

**Comment by jameslamb** [comment]
@BruceZhaoR could you help us with this one?

**Comment by BruceZhaoR** [comment]
Would like to do when I am not busy at work  : )


From BruceZhao's iPhone.
On 03/04/2019 13:08, James Lamb wrote:

@BruceZhaoR could you help us with this one?

**Comment by jameslamb** [comment]
@BruceZhaoR cool, thanks! we'd love the help!

**Comment by bburns632** [comment]
Hey @BruceZhaoR and @jameslamb, this will be awesome once this is set up.  I am pushing this github issues to the [next milestone](https://github.com/UptakeOpenSource/pkgnet/milestone/3), so it stays top-of-mind after we close the current one.

**Comment by BruceZhaoR** [comment]
I will try to do it this weekend.


On 04/01/2019 11:40, bburns632 wrote:

Hey @BruceZhaoR and @jameslamb, this will be awesome once this is set up. I am pushing this github issues to the next milestone, so it stays top-of-mind after we close the current one.

**Comment by BruceZhaoR** [comment]
done !  `[![AppVeyor build status](https://ci.appveyor.com/api/projects/status/github/BruceZhaoR/pkgnet?branch=master&svg=true)](https://ci.appveyor.com/project/BruceZhaoR/pkgnet)`
you can modify this and add  to README
