### ISSUE TITLE
PackageFunctionReporter$calculate_metrics(): error in covr but not tests

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#43]
Oddly, with PR #42,  `devtools::test(".")` returns a success, no issues found with the unit tests.  

```
> devtools::test(".")
Loading pkgnet
Testing pkgnet
Abstract Graph Reporter Tests: ....
Abstract Package Reporter Tests: ....
CreatePackageReport: ..
Creation of graph of package functions: ...........
Package Dependency Reporter Tests: ........................
Package Function Reporter Tests: ...................NULL
.......

DONE ==================================================================================================
> 
```

However, `covr::package_coverage(".")` returns the following issue: 
```
> testthat::test_check('pkgnet')
NULL
1. Failure: PackageFunctionReporter Methods Work (@test-PackageFunctionReporter.R#127) 
testObj$calculate_metrics() produced warnings.


testthat results ================================================================
OK: 78 SKIPPED: 0 FAILED: 1
1. Failure: PackageFunctionReporter Methods Work (@test-PackageFunctionReporter.R#127) 

Error: testthat unit tests failed
Execution halted
```

At the moment, this just means we cannot evaluate the coverage of package net.  We can still instate the unit tests and associated code.  

It has proven a difficult bug to remedy.  Help is appreciated.

**Comment by bburns632** [comment]
@jayqi was this addressed in your last PR?

**Comment by jameslamb** [comment]
I just ran this on most recent `master` and this is fixed! we can close this issue

![image](https://user-images.githubusercontent.com/7608904/36636357-f6bb65aa-198a-11e8-8822-f907414ce9a0.png)
