### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#47]
Does it make sense to have a style guide? Otherwise it's confusing what we should be doing in terms of:
- Method names
- Variable names
- How to write roxygen documentation
- Best way to comment stuff inline
- Indent length
- Commas

Maybe merge with the [CONDUCT.md](https://github.com/UptakeOpenSource/pkgnet/blob/master/CONDUCT.md) into a CONTRIBUTING.md?

**Comment by jameslamb** [comment]
I would prefer to have a separate `CONTRIBUTING.md` that just links to the `CONDUCT.md`. But yes, I like this
