### ISSUE TITLE
Network Plots Not Rendering in HTML Reports

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#56]
Sometimes the dependency or functional networks do not show in the created HTML report.

**Comment by bburns632** [comment]
After switching the order of the reporters, this appears to be specific to the dependency reporter

**Comment by bburns632** [comment]
Nevermind.  It is not consistent.  I reran the same report and all plots rendered fine.

**Comment by jameslamb** [comment]
@bburns632 can we close this one?

**Comment by bburns632** [comment]
Yeah.  They look pretty bad for large graphs right now, but they render.

On Mar 19, 2018 10:03 PM, "James Lamb" <notifications@github.com> wrote:

@bburns632 <https://github.com/bburns632> can we close this one?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/UptakeOpenSource/pkgnet/issues/56#issuecomment-374456890>,
or mute the thread

**Comment by jayqi** [comment]
Whatever was going on back in February/March got resolved, so going to close this issue.
