### ISSUE TITLE
Precision is inconsisent in report tables

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#64]
Tables produced by `get_summary_view()` produce inconsistent precision. Should add some kind of rounding

![image](https://user-images.githubusercontent.com/7608904/37051133-3ed411cc-213b-11e8-94ae-b07ff352b2c6.png)

**Comment by adam-m-mcelhinney** [comment]
@jameslamb on it.

**Comment by adam-m-mcelhinney** [comment]
@jameslamb @bburns632 PR here: https://github.com/UptakeOpenSource/pkgnet/pull/87
