### ISSUE TITLE
pkg_path in CreatePackageReport needs to be an absolute path

### ISSUE THREAD

**Issue by mfrasco6** [UptakeOpenSource/pkgnet#77]
The documentation in `CreatePackageReport` does not specify whether the argument `pkg_path` needs to be an absolute path. However, when I used a relative path, I got the following error ` Error: `path` is invalid: <my_relative_path>`.

Is this the intended behavior? And, if it is, would you be open to a PR where I clarified the documentation?

Thanks for the package!

**Comment by jameslamb** [comment]
hey thank you for reporting this! We would welcome a PR to fix it. A fix would look like:

1. More explicit docs
2. use of `tools::file_path_as_absolute()` for safety
3. tests on the expected behavior

**Comment by mfrasco** [comment]
this issue is closed by this PR: https://github.com/UptakeOpenSource/pkgnet/pull/80
