### ISSUE TITLE
Missing edges in function graphs

### ISSUE THREAD

**Issue by wlandau** [UptakeOpenSource/pkgnet#79]
I am really excited for this package! It is a promising improvement relative to [the static visual displays of call graphs from `CodeDepends`](https://cran.r-project.org/web/packages/CodeDepends/vignettes/intro.html#call-graphs) (ref: https://github.com/duncantl/CodeDepends/issues/18).

For `CreatePackageReport(pkg_name = "liteq")`, here are some screenshots of the function graph. `ack()` calls `db_ack()` and `consume()` calls `db_consume()`, but the graph does not show this information.

![screenshot_20180414_211701](https://user-images.githubusercontent.com/1580860/38773973-98ea6136-4029-11e8-9c45-133245587f74.png)

![screenshot_20180414_211737](https://user-images.githubusercontent.com/1580860/38773974-9c87d7e2-4029-11e8-9d26-236efc4fd0a4.png)

**Comment by jameslamb** [comment]
@wlandau thanks for trying out the package and for reporting this. We will take a look!

**Comment by wlandau** [comment]
Thanks! I suspect this is related to #22. I see now that [`mvbutils::foodweb()` is used to find the edges](https://github.com/UptakeOpenSource/pkgnet/blob/master/R/PackageFunctionReporter.R#L172). I recommend [`CodeDepends`](https://github.com/duncantl/codedepends) for this task. You could even borrow [`makeCallGraph()`](https://cran.r-project.org/web/packages/CodeDepends/vignettes/intro.html#call-graphs) and save yourself some trouble. cc @gmbecker and @duncantl.

**Comment by jameslamb** [comment]
Cool! We have had #22 on our radar for a while, but weren't really sure how to tackle it. 

I can't speak for @bburns632 but at least I personally wasn't aware of `CodeDepends` before. Seems like it might be a good option

**Comment by bburns632** [comment]
Thanks for pointing us to `CodeDepends`.  I wasn't aware of it before.  I definitely want to try [makeCallGraph()](https://cran.r-project.org/web/packages/CodeDepends/vignettes/intro.html#call-graphs) to address our function network issues and #22 .  

Also, the temporal variable definition plots at the bottom of that vignette are intriguing.

**Comment by jameslamb** [comment]
Hey @wlandau sorry for the delay, but I THINK I might know what's going on here!

I finally replaced `mvbutils` tonight (#120 ). I decided not to remove one dependency and replace it with another, so I wrote this up in pure R plus `data.table` code (taking some inspiration from `mvbutils`).

We use this approach to extract the names of functions (assume for simplicity all objects in the package are functions):

```
funs <- ls("package:liteq")
```

This, however, only lists symbols _exported_ from that namespace! You can see that by comparing `funs` to this:

```
funs2 <- names(as.list(loadNamespace("liteq")))
```

`ack()`, for example, is exported but we never pick up the dependency to `db_ack()` because `db_ackI)` is internal.

@bburns632 I think we should open an issue about adding support for non-exported functions to `PackageFunctionReporter`. Is that consistent with your intent for the package?

**Comment by wlandau** [comment]
Thanks for following up.

> This, however, only lists symbols exported from that namespace!

[`drake`](https://github.com/ropensci/drake) had a similar problem for a while, and @dapperjapper found a [neat trick that uses `environment<-`](https://github.com/ropensci/drake/blob/fe5c9a50ce6bc7b03ba122c676632d0d2fae1b0c/R/expose_imports.R#L103-L118).

**Comment by jayqi** [comment]
@wlandau I think #122 that we just merged should fix your issue:

``` r
library(pkgnet)

foo <- FunctionReporter$new()
foo$set_package('liteq')
#> INFO [2018-11-14 16:29:33] Checking installed packages...
#> INFO [2018-11-14 16:29:33] Found 'liteq' in installed packages.
#> INFO [2018-11-14 16:29:33] Resetting cached network information...
foo$nodes[node %in% c('db_ack', 'db_consume')]
#> INFO [2018-11-14 16:29:33] Calling extract_network() to extract nodes and edges...
#> INFO [2018-11-14 16:29:33] Resetting cached network information...
#> INFO [2018-11-14 16:29:33] Extracting nodes from liteq...
#> INFO [2018-11-14 16:29:33] Done extracting nodes.
#> INFO [2018-11-14 16:29:33] Extracting edges from liteq...
#> INFO [2018-11-14 16:29:33] Constructing network representation...
#> INFO [2018-11-14 16:29:33] Done constructing network representation
#> INFO [2018-11-14 16:29:33] Done extracting edges.
#>          node     type isExported
#> 1:     db_ack function      FALSE
#> 2: db_consume function      FALSE
foo$edges[SOURCE %in% c('db_ack', 'db_consume')]
#>        SOURCE  TARGET
#> 1: db_consume consume
#> 2:     db_ack    nack
#> 3:     db_ack     ack
```

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Let me know if that isn't the case and we can reopen the issue! :)

**Comment by wlandau** [comment]
Glad to know, thanks for the patch. It looks like the unexported `db_consume()` is now detected.
