### ISSUE TITLE
Package documentation should use inheritParams

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#81]
Some arguments like `pkg_name` and `pkg_path` are repeated several times in the documentation. We should centralize them using `#' @inheritParams` from `roxygen2`

**Comment by jameslamb** [comment]
an example of doing this: https://github.com/UptakeOpenSource/uptasticsearch/blob/master/r-pkg/R/uptasticsearch.R#L20

**Comment by richagg** [comment]
I'm trying to fix this. Watch this space!

**Comment by jameslamb** [comment]
@richagg Thank you for agreeing to help us out! Unfortunately another person is already working on this issue and has opened a PR into this repo (#115 )

I want to note that you should have created a pull request into _this repo_, but it looks like you PR'd into https://github.com/cran/pkgnet/pull/1.

Please close out that other PR and look through our Issues page here for something else that you can pick up. We could use the help!!

Cheers,

-James

**Comment by richagg** [comment]
Hi James,

Thank you for hosting me at the Uptake Hackathon. I had never made a PR
before and someone at the mentor table did this for me, I guess it did not
go as plan.
I apologise for the inconvenience, but I did learn what NOT to do :)
Thanks once again and I will ensure to get it right for the next issue I
pick up!

Best,
Richa G
Data Science Intern @ UIC

**Comment by jameslamb** [comment]
@richagg no problem at all. We hope you'll come back to contribute!

**Comment by jameslamb** [comment]
this was fixed by #115
